version: '3.7'

services:
  app:
    container_name: linkedregistrations-ui
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    env_file:
      - .env
      - .env.local
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - './src:/app/src'

networks:
  default:
    name: helsinki
