version: '3.7'

services:
  app:
    container_name: linkedregistrations-ui
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - './src:/app/src'
