name: Build & Staging
on:
  push:
    branches:
      - develop

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  SERVICE_PORT: 3000
  K8S_REQUEST_CPU: 100m
  K8S_REQUEST_RAM: 400Mi
  K8S_LIMIT_CPU: 800m
  K8S_LIMIT_RAM: 800Mi
  K8S_REPLICACOUNT: 2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging
          DOCKER_BUILD_ARG_NEXT_ENV: 'production'
          DOCKER_BUILD_ARG_NEXT_PUBLIC_LINKED_EVENTS_URL: 'https://linkedevents-api.dev.hel.ninja/linkedevents-dev/v1'
          DOCKER_BUILD_ARG_NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
          DOCKER_BUILD_ARG_SENTRY_AUTH_TOKEN: ${{ secrets.GH_SENTRY_AUTH_TOKEN }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_ENVIRONMENT: 'staging'
          DOCKER_BUILD_ARG_OIDC_ISSUER: 'https://api.hel.fi/sso'
          DOCKER_BUILD_ARG_OIDC_API_TOKENS_URL: 'https://api.hel.fi/sso/api-tokens/'
          DOCKER_BUILD_ARG_OIDC_CLIENT_ID: 'linkedcomponents-ui-test'
          DOCKER_BUILD_ARG_OIDC_LINKED_EVENTS_API_SCOPE: 'https://api.hel.fi/auth/linkedeventsdev'
          DOCKER_BUILD_ARG_OIDC_TOKEN_URL: 'https://api.hel.fi/sso/token/'
          DOCKER_BUILD_ARG_NEXTAUTH_SECRET: ${{ secrets.GH_NEXTAUTH_SECRET_STAGING }}
          DOCKER_BUILD_ARG_NEXTAUTH_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}

  staging:
    runs-on: ubuntu-latest
    needs: build
    name: Staging
    steps:
      - uses: actions/checkout@v3
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'staging'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-staging
